services:
  mini-project-gamified-habit-tracker-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mini_project_gamified_habit_tracker_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - mini-project-gamified-habit-tracker-db-data:/var/lib/postgresql/data
    ports:
      - "5445:5432"

  mini-project-gamified-habit-tracker-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - mini-project-gamified-habit-tracker-redis-data:/data
    restart: always
    command: [ "redis-server", "--requirepass", "password" ]

  mini-project-gamified-habit-tracker-minio:
    image: minio/minio:latest
    command: server /var/lib/minio/data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9005:9000"
      - "9006:9001"
    volumes:
      - mini-project-gamified-habit-tracker-storage:/var/lib/minio/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s

  minio-init:
    image: minio/mc
    depends_on:
      mini-project-gamified-habit-tracker-minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO to be fully ready...' &&
      sleep 10 &&
      echo 'Configuring MinIO client...' &&
      mc config host add myminio http://mini-project-gamified-habit-tracker-minio:9000 admin password &&
      echo 'Creating bucket...' &&
      mc mb --ignore-existing myminio/mini-project-gamified-habit-tracker-bucket &&
      echo 'Adding user...' &&
      mc admin user add myminio miniprojectkey miniprojectgamifiedhabittrackersecret &&
      echo 'Setting policy...' &&
      mc admin policy set readwrite myminio user=miniprojectkey &&
      echo 'MinIO initialization completed successfully'
      "
    restart: on-failure
  
  mini-project-gamified-habit-tracker-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9085:8080"
    environment:
      MINIO_URL: http://mini-project-gamified-habit-tracker-minio:9000
      MINIO_ACCESS_KEY: miniprojectkey
      MINIO_ACCESS_SECRET: miniprojectgamifiedhabittrackersecret
      MINIO_BUCKET_NAME: mini-project-gamified-habit-tracker-bucket
      SPRING_DATA_REDIS_HOST: mini-project-gamified-habit-tracker-redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://mini-project-gamified-habit-tracker-db:5432/mini_project_gamified_habit_tracker_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mini-project-gamified-habit-tracker-db
      - mini-project-gamified-habit-tracker-redis
      - mini-project-gamified-habit-tracker-minio

volumes:
  mini-project-gamified-habit-tracker-storage:
  mini-project-gamified-habit-tracker-db-data:
  mini-project-gamified-habit-tracker-redis-data: